# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import blind_pb2 as blind__pb2

GRPC_GENERATED_VERSION = '1.83.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in blind_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SchedulerStub:
    """---- Service ----

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitRun = channel.unary_unary(
                '/blind.Scheduler/SubmitRun',
                request_serializer=blind__pb2.RunRequest.SerializeToString,
                response_deserializer=blind__pb2.RunHandle.FromString,
                _registered_method=True)
        self.GetTask = channel.unary_unary(
                '/blind.Scheduler/GetTask',
                request_serializer=blind__pb2.WorkerId.SerializeToString,
                response_deserializer=blind__pb2.Task.FromString,
                _registered_method=True)
        self.ReportResult = channel.unary_unary(
                '/blind.Scheduler/ReportResult',
                request_serializer=blind__pb2.TaskResult.SerializeToString,
                response_deserializer=blind__pb2.Empty.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/blind.Scheduler/Heartbeat',
                request_serializer=blind__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=blind__pb2.Empty.FromString,
                _registered_method=True)
        self.GetRun = channel.unary_unary(
                '/blind.Scheduler/GetRun',
                request_serializer=blind__pb2.RunId.SerializeToString,
                response_deserializer=blind__pb2.Leaderboard.FromString,
                _registered_method=True)


class SchedulerServicer:
    """---- Service ----

    """

    def SubmitRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTask(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReportResult(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRun(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SchedulerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitRun': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitRun,
                    request_deserializer=blind__pb2.RunRequest.FromString,
                    response_serializer=blind__pb2.RunHandle.SerializeToString,
            ),
            'GetTask': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTask,
                    request_deserializer=blind__pb2.WorkerId.FromString,
                    response_serializer=blind__pb2.Task.SerializeToString,
            ),
            'ReportResult': grpc.unary_unary_rpc_method_handler(
                    servicer.ReportResult,
                    request_deserializer=blind__pb2.TaskResult.FromString,
                    response_serializer=blind__pb2.Empty.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=blind__pb2.HeartbeatRequest.FromString,
                    response_serializer=blind__pb2.Empty.SerializeToString,
            ),
            'GetRun': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRun,
                    request_deserializer=blind__pb2.RunId.FromString,
                    response_serializer=blind__pb2.Leaderboard.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'blind.Scheduler', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('blind.Scheduler', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class Scheduler:
    """---- Service ----

    """

    @staticmethod
    def SubmitRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blind.Scheduler/SubmitRun',
            blind__pb2.RunRequest.SerializeToString,
            blind__pb2.RunHandle.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTask(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blind.Scheduler/GetTask',
            blind__pb2.WorkerId.SerializeToString,
            blind__pb2.Task.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReportResult(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blind.Scheduler/ReportResult',
            blind__pb2.TaskResult.SerializeToString,
            blind__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blind.Scheduler/Heartbeat',
            blind__pb2.HeartbeatRequest.SerializeToString,
            blind__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetRun(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/blind.Scheduler/GetRun',
            blind__pb2.RunId.SerializeToString,
            blind__pb2.Leaderboard.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
